[package]
name = "maya-crdt"
version = "0.1.0"
edition = "2024"

[dependencies] 
chrono = { version = "0.4", features = ["clock"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
hostname = "0.3"
sha2 = "0.10"


[profile.release]
opt-level = 3
lto = true
strip = true